[connections.mongodb]
url="mongodb+srv://test:test@reddit-data.xoh1bzr.mongodb.net/?retryWrites=true&w=majority"
database="streamlit"
collection="connection"

[connections.mongodb.kwargs]
retryWrites=true
w="majority"
maxIdleTimeMS=180000
serverSelectionTimeoutMS=2000